version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  postgres:
    image: postgres:9.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      OSTGRES_PASSWORD: root